const quotes = [

    { id: 1, quote: "배움에는 끝이 없고, 노력은 반드시 결과를 만든다.", author: "공자", category: "공부" },
    { id: 2, quote: "성공은 작은 노력들이 모여 만들어지는 결과이다.", author: "로버트 콜리어", category: "성공" },
    { id: 3, quote: "위대한 리더는 사람들에게 명령하는 사람이 아니라 영감을 주는 사람이다.", author: "존 C. 맥스웰", category: "리더십" },
    { id: 4, quote: "생각하는 삶이야말로 진정한 삶이다.", author: "소크라테스", category: "철학" },
    { id: 5, quote: "기회를 기다리지 말고 스스로 기회를 만들어라.", author: "조지 버나드 쇼", category: "창업" },
    { id: 6, quote: "인생은 속도가 아니라 방향이 중요하다.", author: "알 수 없음", category: "인생" },
    { id: 7, quote: "실패는 끝이 아니라 더 나은 시작을 위한 과정이다.", author: "토마스 에디슨", category: "성공" },
    { id: 8, quote: "오늘의 작은 습관이 미래의 나를 만든다.", author: "제임스 클리어", category: "공부" },
    { id: 9, quote: "좋은 리더는 먼저 듣고, 그 다음 행동한다.", author: "피터 드러커", category: "리더십" },
    { id: 10, quote: "자신을 아는 것이 모든 지혜의 시작이다.", author: "아리스토텔레스", category: "철학" },
    { id: 11, quote: "새로운 길을 만드는 사람이 새로운 시대를 만든다.", author: "스티브 잡스", category: "창업" },
    { id: 12, quote: "행복은 목적지가 아니라 여행하는 과정이다.", author: "랄프 왈도 에머슨", category: "인생" },

    { id: 13, quote: "리더십은 다른 사람들이 빛날 수 있는 무대를 만드는 것입니다.", author: "젠슨 황", category: "리더십" },
    { id: 14, quote: "나는 항상 30일 뒤에 망한다는 마음가짐으로 일한다.", author: "젠슨 황", category: "성공" },
    { id: 15, quote: "정말 중요한 일이라면, 성공 확률이 낮더라도 그 일을 계속해야 합니다.", author: "일론 머스크", category: "창업" },
    { id: 16, quote: "나는 비관적으로 옳기보다는, 낙관적으로 틀리는 쪽을 택하겠다.", author: "일론 머스크", category: "인생" },
    { id: 17, quote: "뜨거운 간절함으로 새로운 시대를 선도하자.", author: "이길여", category: "인생" },
    { id: 18, quote: "좋은 평판을 쌓는 데는 20년이 걸리지만, 무너지는 데는 5분이면 충분하다.", author: "워런 버핏", category: "성공" },

    // ── 공부 (19-33) ──
    { id: 19, quote: "지식에 대한 투자는 항상 최고의 이자를 가져다준다.", author: "벤저민 프랭클린", category: "공부" },
    { id: 20, quote: "교육은 세상을 바꿀 수 있는 가장 강력한 무기다.", author: "넬슨 만델라", category: "공부" },
    { id: 21, quote: "내일 죽을 것처럼 살고, 영원히 살 것처럼 배워라.", author: "마하트마 간디", category: "공부" },
    { id: 22, quote: "나는 특별한 재능이 없다. 다만 열정적으로 호기심이 많을 뿐이다.", author: "아인슈타인", category: "공부" },
    { id: 23, quote: "인생에서 두려워할 것은 없다. 다만 이해해야 할 것이 있을 뿐이다.", author: "마리 퀴리", category: "공부" },
    { id: 24, quote: "교육은 미래로 향하는 여권이다.", author: "맬컴 엑스", category: "공부" },
    { id: 25, quote: "아는 것을 안다고 하고 모르는 것을 모른다고 하는 것, 그것이 참된 앎이다.", author: "공자", category: "공부" },
    { id: 26, quote: "질문을 멈추지 않는 사람이 결국 답을 찾는다.", author: "클로드", category: "공부" },
    { id: 27, quote: "오늘 배운 한 줄이 내일의 무기가 된다.", author: "클로드", category: "공부" },
    { id: 28, quote: "모르는 것을 인정하는 순간, 배움은 시작된다.", author: "클로드", category: "공부" },
    { id: 29, quote: "재능은 반복 앞에서 무릎을 꿇는다.", author: "클로드", category: "공부" },
    { id: 30, quote: "느리게 걸어도 멈추지 않는 사람이 결국 가장 멀리 간다.", author: "클로드", category: "공부" },
    { id: 31, quote: "가장 좋은 스승은 어제의 실수다.", author: "클로드", category: "공부" },
    { id: 32, quote: "배움에 지름길은 없지만, 방향은 있다.", author: "클로드", category: "공부" },
    { id: 33, quote: "이해하지 못한 채 외운 지식은 오래가지 않는다.", author: "클로드", category: "공부" },

    // ── 성공 (34-46) ──
    { id: 34, quote: "행운이란 준비가 기회를 만났을 때 일어나는 일이다.", author: "세네카", category: "성공" },
    { id: 35, quote: "위대한 일을 이루는 유일한 방법은 자신이 하는 일을 사랑하는 것이다.", author: "스티브 잡스", category: "성공" },
    { id: 36, quote: "나는 계속해서 실패했다. 그것이 내가 성공한 이유다.", author: "마이클 조던", category: "성공" },
    { id: 37, quote: "천재는 1퍼센트의 영감과 99퍼센트의 노력으로 이루어진다.", author: "토마스 에디슨", category: "성공" },
    { id: 38, quote: "할 수 있다고 믿든 할 수 없다고 믿든, 당신의 생각이 옳다.", author: "헨리 포드", category: "성공" },
    { id: 39, quote: "성공은 포기하지 않은 사람에게 남은 마지막 선택지다.", author: "클로드", category: "성공" },
    { id: 40, quote: "작은 승리를 무시하는 사람은 큰 승리도 알아보지 못한다.", author: "클로드", category: "성공" },
    { id: 41, quote: "성공은 목적지가 아니라 방향을 지킨 결과다.", author: "클로드", category: "성공" },
    { id: 42, quote: "잘 될 때 겸손하고, 안 될 때 흔들리지 않는 것이 진짜 실력이다.", author: "클로드", category: "성공" },
    { id: 43, quote: "포기하지 않는 것도 하나의 전략이다.", author: "클로드", category: "성공" },
    { id: 44, quote: "성공한 사람은 남들이 쉬는 시간에 한 걸음 더 걸은 사람이다.", author: "클로드", category: "성공" },
    { id: 45, quote: "실패를 두려워하지 않는 것이 아니라, 실패 후에도 계속하는 것이 성공이다.", author: "클로드", category: "성공" },
    { id: 46, quote: "결과보다 방향이 맞았는지를 먼저 점검하라.", author: "클로드", category: "성공" },

    // ── 리더십 (47-60) ──
    { id: 47, quote: "리더는 양치기와 같다. 무리 뒤에 서서 가장 기민한 이들을 앞서가게 하되, 정작 이끌고 있다는 것은 아무도 모르게 한다.", author: "넬슨 만델라", category: "리더십" },
    { id: 48, quote: "당신의 행동이 다른 사람들로 하여금 더 많이 꿈꾸고, 더 많이 배우고, 더 많이 행동하도록 영감을 준다면, 당신은 리더다.", author: "존 퀸시 애덤스", category: "리더십" },
    { id: 49, quote: "리더십은 사람들이 해야 할 일을 스스로 하고 싶게 만드는 기술이다.", author: "아이젠하워", category: "리더십" },
    { id: 50, quote: "경영은 일을 옳게 하는 것이고, 리더십은 옳은 일을 하는 것이다.", author: "피터 드러커", category: "리더십" },
    { id: 51, quote: "리더는 특권이 아니라 책임을 먼저 짊어지는 사람이다.", author: "사이먼 시넥", category: "리더십" },
    { id: 52, quote: "리더의 말보다 리더의 행동이 팀을 움직인다.", author: "클로드", category: "리더십" },
    { id: 53, quote: "믿어주는 것이 가장 강력한 동기부여다.", author: "클로드", category: "리더십" },
    { id: 54, quote: "좋은 리더는 정답을 주지 않고 질문을 남긴다.", author: "클로드", category: "리더십" },
    { id: 55, quote: "위기 앞에서 침착한 사람이 결국 팀을 살린다.", author: "클로드", category: "리더십" },
    { id: 56, quote: "공을 나누는 리더가 오래간다.", author: "클로드", category: "리더십" },
    { id: 57, quote: "리더십은 완벽함이 아니라 책임감에서 나온다.", author: "클로드", category: "리더십" },
    { id: 58, quote: "듣는 만큼 이끌 수 있다.", author: "클로드", category: "리더십" },
    { id: 59, quote: "가장 낮은 자리에서도 방향을 제시하는 사람이 리더다.", author: "클로드", category: "리더십" },
    { id: 60, quote: "리더는 팀의 실패를 자신의 실패처럼 받아들인다.", author: "클로드", category: "리더십" },

    // ── 철학 (61-74) ──
    { id: 61, quote: "나를 죽이지 못하는 고통은 나를 더 강하게 만든다.", author: "니체", category: "철학" },
    { id: 62, quote: "정복해야 할 첫 번째이자 가장 위대한 승리는 자기 자신을 정복하는 것이다.", author: "플라톤", category: "철학" },
    { id: 63, quote: "나는 생각한다, 고로 존재한다.", author: "데카르트", category: "철학" },
    { id: 64, quote: "덕이 있는 사람은 외롭지 않다. 반드시 함께하는 이가 있다.", author: "공자", category: "철학" },
    { id: 65, quote: "천 리 길도 한 걸음부터 시작된다.", author: "노자", category: "철학" },
    { id: 66, quote: "우리의 삶은 우리가 하는 생각으로 이루어진다.", author: "마르쿠스 아우렐리우스", category: "철학" },
    { id: 67, quote: "질문을 멈추는 순간 사유도 멈춘다.", author: "클로드", category: "철학" },
    { id: 68, quote: "존재는 설명이 아니라 경험으로 알 수 있다.", author: "클로드", category: "철학" },
    { id: 69, quote: "완벽한 답보다 정직한 질문이 낫다.", author: "클로드", category: "철학" },
    { id: 70, quote: "자유란 선택의 결과를 스스로 책임지는 것이다.", author: "클로드", category: "철학" },
    { id: 71, quote: "고통을 이해하려는 시도 자체가 지혜의 시작이다.", author: "클로드", category: "철학" },
    { id: 72, quote: "시간은 흘러가는 것이 아니라 쌓이는 것이다.", author: "클로드", category: "철학" },
    { id: 73, quote: "타인을 이해하려는 노력이 곧 나를 이해하는 길이다.", author: "클로드", category: "철학" },
    { id: 74, quote: "불확실함을 견디는 힘이 곧 성숙함이다.", author: "클로드", category: "철학" },

    // ── 창업 (75-88) ──
    { id: 75, quote: "1일차의 정신을 유지하라. 2일차가 되는 순간 정체가 시작된다.", author: "제프 베이조스", category: "창업" },
    { id: 76, quote: "경쟁은 패자들이나 하는 것이다.", author: "피터 틸", category: "창업" },
    { id: 77, quote: "이봐, 해봤어?", author: "정주영", category: "창업" },
    { id: 78, quote: "당신의 제품 첫 버전이 부끄럽지 않다면, 이미 너무 늦게 출시한 것이다.", author: "리드 호프먼", category: "창업" },
    { id: 79, quote: "완벽한 계획보다 빠른 실행이 창업가를 만든다.", author: "클로드", category: "창업" },
    { id: 80, quote: "고객의 불편함이 곧 사업의 기회다.", author: "클로드", category: "창업" },
    { id: 81, quote: "작게 시작해서 빠르게 검증하라.", author: "클로드", category: "창업" },
    { id: 82, quote: "창업은 확신이 아니라 의심을 관리하는 일이다.", author: "클로드", category: "창업" },
    { id: 83, quote: "돈보다 먼저 문제를 팔아라.", author: "클로드", category: "창업" },
    { id: 84, quote: "혼자 빨리 가기보다 함께 멀리 가라.", author: "클로드", category: "창업" },
    { id: 85, quote: "실패한 시도는 데이터고, 포기한 시도만 진짜 실패다.", author: "클로드", category: "창업" },
    { id: 86, quote: "시장은 정답을 알려주지 않는다. 다만 반응할 뿐이다.", author: "클로드", category: "창업" },
    { id: 87, quote: "창업가는 위기를 없애는 사람이 아니라 위기에 익숙해지는 사람이다.", author: "클로드", category: "창업" },
    { id: 88, quote: "첫 고객 한 명이 백 개의 아이디어보다 낫다.", author: "클로드", category: "창업" },

    // ── 인생 (89-100) ──
    { id: 89, quote: "인생은 과감한 모험이거나 아무것도 아니다.", author: "헬렌 켈러", category: "인생" },
    { id: 90, quote: "20년 후 당신은 한 일보다 하지 않은 일 때문에 더 실망할 것이다.", author: "마크 트웨인", category: "인생" },
    { id: 91, quote: "가장 큰 영광은 한 번도 넘어지지 않는 것이 아니라 넘어질 때마다 다시 일어서는 것이다.", author: "공자", category: "인생" },
    { id: 92, quote: "당신이 무엇이 되고 싶은지 알고 있다면, 이미 절반은 이룬 것이다.", author: "랄프 왈도 에머슨", category: "인생" },
    { id: 93, quote: "인생은 속도보다 방향이 중요할 때가 더 많다.", author: "클로드", category: "인생" },
    { id: 94, quote: "오늘 하루를 소홀히 하는 사람은 내일도 소홀히 한다.", author: "클로드", category: "인생" },
    { id: 95, quote: "비교는 불행으로 가는 가장 빠른 지름길이다.", author: "클로드", category: "인생" },
    { id: 96, quote: "완벽한 타이밍은 없다. 시작한 순간이 타이밍이다.", author: "클로드", category: "인생" },
    { id: 97, quote: "잃은 것을 세지 말고 남은 것을 세라.", author: "클로드", category: "인생" },
    { id: 98, quote: "행복은 크기가 아니라 빈도다.", author: "클로드", category: "인생" },
    { id: 99, quote: "천천히 가더라도 나답게 가는 것이 결국 가장 빠른 길이다.", author: "클로드", category: "인생" },
    { id: 100, quote: "인생의 의미는 찾는 것이 아니라 만들어가는 것이다.", author: "클로드", category: "인생" }

];

